//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/MapSoloCamara.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MapSoloCamara: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MapSoloCamara()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MapSoloCamara"",
    ""maps"": [
        {
            ""name"": ""Camara"",
            ""id"": ""1b734386-19dc-4d6c-8650-ab88ee605fc6"",
            ""actions"": [
                {
                    ""name"": ""Camara"",
                    ""type"": ""Value"",
                    ""id"": ""00fa7483-966b-4921-bcbb-2bf8e3a4c3a3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f4594fa2-c731-42b4-9837-04d9680849bd"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camara"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Camara
        m_Camara = asset.FindActionMap("Camara", throwIfNotFound: true);
        m_Camara_Camara = m_Camara.FindAction("Camara", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Camara
    private readonly InputActionMap m_Camara;
    private List<ICamaraActions> m_CamaraActionsCallbackInterfaces = new List<ICamaraActions>();
    private readonly InputAction m_Camara_Camara;
    public struct CamaraActions
    {
        private @MapSoloCamara m_Wrapper;
        public CamaraActions(@MapSoloCamara wrapper) { m_Wrapper = wrapper; }
        public InputAction @Camara => m_Wrapper.m_Camara_Camara;
        public InputActionMap Get() { return m_Wrapper.m_Camara; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CamaraActions set) { return set.Get(); }
        public void AddCallbacks(ICamaraActions instance)
        {
            if (instance == null || m_Wrapper.m_CamaraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CamaraActionsCallbackInterfaces.Add(instance);
            @Camara.started += instance.OnCamara;
            @Camara.performed += instance.OnCamara;
            @Camara.canceled += instance.OnCamara;
        }

        private void UnregisterCallbacks(ICamaraActions instance)
        {
            @Camara.started -= instance.OnCamara;
            @Camara.performed -= instance.OnCamara;
            @Camara.canceled -= instance.OnCamara;
        }

        public void RemoveCallbacks(ICamaraActions instance)
        {
            if (m_Wrapper.m_CamaraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICamaraActions instance)
        {
            foreach (var item in m_Wrapper.m_CamaraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CamaraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CamaraActions @Camara => new CamaraActions(this);
    public interface ICamaraActions
    {
        void OnCamara(InputAction.CallbackContext context);
    }
}
